version: 2

models:
  - name: stg_listings
    columns:
      - name: listing_id
        tests:
          - not_null
          - unique

      - name: price
        tests:
          - not_null

      - name: room_type
        tests:
          - not_null

  - name: stg_reviews
    columns:
      - name: listing_id
        tests:
          - not_null

  - name: dim_listings
    columns:
      - name: listing_id
        tests:
          - not_null
          - unique